version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      php: 8.2
  pre_build:
    on-failure: ABORT
    commands:
      - echo Nothing to do in the pre_build phase...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 570033531346.dkr.ecr.ap-northeast-1.amazonaws.com
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - docker build -t api .
      - docker tag api:latest 570033531346.dkr.ecr.ap-northeast-1.amazonaws.com/api:latest
  post_build:
    on-failure: ABORT
    commands:
      - echo Build completed on `date`
      - docker push 570033531346.dkr.ecr.ap-northeast-1.amazonaws.com/api:latest