version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      php: 8.2
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    on-failure: ABORT
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
  post_build:
    on-failure: ABORT
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/messageUtil-1.0.jar